services:
  patients:
    container_name: patients
    image: patients
    ports:
      - "8081:8081"

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: MediScreenDB
      MYSQL_ROOT_PASSWORD: password